[Expr.Assign]
Fields = [ "Token Name" , "Expr Value" ]
ToString = "{Name} = {Value}"

[Expr.Binary]
Fields = [ "Expr Left", "Token Operator", "Expr Right" ]
ToString = "{Left} {Operator} {Right}"

[Expr.Call]
Fields = [ "Expr Callee", "IList<Expr> Arguments" ]
ToString = "{Callee}({Arguments})"

[Expr.Grouping]
Fields = [ "Expr Expression" ]
ToString = "({Expression})"

[Expr.Literal]
Fields = [ "object Value" ]
ToString = "{Value}"

[Expr.Object]
Fields = [ "IDictionary<Expr, Expr> Values" ]
ToString = "{{{string.Join(',', Values.Select(kvp => kvp.Key.ToString() + ':' + kvp.Value.ToString()))}}}"

[Expr.Array]
Fields = [ "IList<Expr> Values" ]
ToString = "[{string.Join(',', Values)}]"

[Expr.Logical]
Fields = [ "Expr Left", "Token Operator", "Expr Right" ]
ToString = "{Left} {Operator} {Right}"

[Expr.Unary]
Fields = [ "Token Operator", "Expr Right" ]
ToString = "{Operator}{Right}"

[Expr.Variable]
Fields = [ "Token Name" ]
ToString = "{Name}"

[Stmt.Block]
Fields = [ "IList<Stmt> Statements" ]
ToString = "{Statements}"

[Stmt.Expression]
Fields = [ "Expr Expr" ]
ToString = "{Expr}"

[Stmt.Namespace]
Fields = [ "Token Name", "Stmt Body" ]
ToString = "namespace {Name} {Body}"

[Stmt.Function]
Fields = [ "Token Name", "IList<Token> Params", "Stmt Body" ]
ToString = "function {Name}({Params}) {Body}"

[Stmt.If]
Fields = [ "Expr Condition", "Stmt ThenBranch", "Stmt? ElseBranch" ]
ToString = "if {Condition} then {ThenBranch} else {ElseBranch}"

[Stmt.Debug]
Fields = [ "Expr Expr" ]
ToString = "debug {Expr}"

[Stmt.Comment]
Fields = [ "Token Value" ]
ToString = "# {Value}"

[Stmt.Return]
Fields = [ "Expr? Value" ]
ToString = "return {Value}"

[Stmt.Break]
Fields = [ ]
ToString = "break"

[Stmt.Continue]
Fields = [ ]
ToString = "continue"

[Stmt.Var]
Fields = [ "Token Name", "Expr? Initializer" ]
ToString = "var {Name} = {Initializer}"

[Stmt.While]
Fields = [ "Expr Condition", "Stmt Body" ]
ToString = "while {Condition} do {Body}"