namespace Amethyst;

public enum TokenType
{
    KWD_FUNCTION,
    KWD_TICKING,
    KWD_INITIALIZING,
    KWD_NAMESPACE,
    KWD_VARIABLE,
    PAREN_OPEN,
    PAREN_CLOSE,
    BRACE_OPEN,
    BRACE_CLOSE,
    BRACKET_OPEN,
    BRACKET_CLOSE,
    LITERAL_STRING,
    LITERAL_NUMBER,
    IDENTIFIER,
    SEMICOLON,
    COMMA,
    OP_ADD,
    OP_SUB,
    OP_MUL,
    OP_DIV,
    OP_MOD,
    OP_ASSIGN
}