 minecraft = "/Users/fabian/Library/Application Support/PrismLauncher/instances/23w33a/.minecraft"

[datapack]
name = "playground"
description = "Test datapack for the amethyst compiler"
output = "New World"

[resourcepack]
name = "playground"
description = "Test resourcepack for the amethyst compiler"